Java try-catch block
--------------------
Java try block is used to enclose the code that might throw an exception. It must be used within the method.
Java try block must be followed by either catch or finally block.

Syntax of Java try-catch
-----------------------
try{    
//code that may throw an exception    
}catch(Exception_class_Name ref){}   

Syntax of try-finally block
----------------------------
try{    
//code that may throw an exception    
}finally{}

Java catch block

Java catch block is used to handle the Exception by declaring the type of exception within the parameter. The declared exception must be the parent class exception( i.e., Exception).
The catch block must be used after the try block only. You can use multiple catch block with a single try block.

Example
--------
public class TryCatchExample2 {  
  
    public static void main(String[] args) {  
        try  
        {  
        int data=50/0; //may throw exception   
        }  
            //handling the exception  
        catch(ArithmeticException e)  
        {  
            System.out.println(e);  
        }  
        System.out.println("rest of the code");  
    }  
      
}  
Output:
------
java.lang.ArithmeticException: / by zero
rest of the code

Customizze Example
-------------------
public class TryCatchExample5 {  
  
    public static void main(String[] args) {  
        try  
        {  
        int data=50/0; //may throw exception   
        }  
             // handling the exception  
        catch(Exception e)  
        {  
                  // displaying the custom message  
            System.out.println("Can't divided by zero");  
        }  
    }  
      
}  

Output:
Can't divided by zero

Example
--------
public class TryCatchExample6 {    
    public static void main(String[] args) {  
        int i=50;  
        int j=0;  
        int data;  
        try  
        {  
        data=i/j; //may throw exception   
        }  
        catch(Exception e)  
        {   
            System.out.println(i/(j+2));  //25
        }  
    }  
} 

unchecked exception Example
---------------------------
public class TryCatchExample9 {  
  
    public static void main(String[] args) {  
        try  
        {  
        int arr[]= {1,3,5,7};  
        System.out.println(arr[10]); //may throw exception   
        }  
        catch(ArrayIndexOutOfBoundsException e)  
        {  
            System.out.println(e);  
        }  
        System.out.println("rest of the code");  
    }     
}  
Output:
java.lang.ArrayIndexOutOfBoundsException: 10
rest of the code

